<script lang="ts" context="module">
	export const blog = [
		{
			title: "India's Journey Towards a Digital Economy",
			preview:
				'On November 8, 2016 the Government announced demonetization, the event that brought digital payments to the fore. Three years forward in 2019 RBI reported that the number of digital transactions has tripled, and now in 2021 the number of transactions has again doubled in volume.',
			content: `<h2>Introduction</h2><p>On November 8, 2016 the Government announced demonetization, the event that brought digital payments to the fore.</p><p>Three years forward in 2019 RBI reported that the number of digital transactions has tripled, and now in 2021 the number of transactions has again doubled in volume. The long ATMs queues are becoming a rare sight. Shopkeepers, cab drivers, and street vendor are switching over to digital payments.</p><p>So, what happened? Why was there a sudden surge in digital transactions? And what does the future hold?</p><h2>Facts and Figures</h2><p>At the present rate of shift towards digital payment systems; 3 in every 4 transactions will be digital by 2025. This sudden momentum can be seen as a result of increasing technological advances in the financial system and events like demonetization and COVID lockdown which acted as a catalyst. The speed, safety, ease of payments attracts vendors and consumers equally.</p><p>Though the currency circulation was increased by 19.1 % in 2019 from the 2016 levels, the RBI norms on withdrawal limits, tariffs on ATM withdrawals, and intensive marketing campaigns by fintech companies has made India the top country in digital transactions by volume.</p><p>The most preferred form of digital payment presently is UPI (Unified Payment Interface) by debit/credit cards. The year 2020 marked a new record for UPI transactions in India. The total UPI transactions in 2020 reached the figure of 4,16,000 crores in 2020 which was a two-fold increase from the transactions in 2019. The pandemic forced many people to be accustomed to these formats, still it’s something that will benefit the economy in long run.</p><h2>Going Forward</h2><p>What does the future hold for digital payment? That&#39;s a really difficult question to answer, but it is sure that we’re not going back to the paper currency age.</p>`,
			img:
				'https://images.unsplash.com/photo-1607434531924-050d4e675a44?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
			date: 'July 16, 2021'
		},
		{
			title: 'Top Three Modes of Digital Payment',
			preview:
				'Gone are the days of waiting in queues to withdraw/deposit cash at the banks. ‘Faceless, Paperless and Cashless’ is the motto of the Digital India Campaign. With this realization, India, in the past 5-6 years, has seen a huge shift in the payment modes.',
			content: `<p><em>Gone are the days of waiting in queues to withdraw/deposit cash at the banks. ‘Faceless, Paperless and Cashless’ is the motto of the Digital India Campaign. With this realization, India, in the past 5-6 years, has seen a huge shift in the payment modes.</em></p><p>Around 39% of the retail transactions in India are done digitally, and this percentage is on the rise. Let’s look at the systems that are slowly replacing paper currency.</p><h2 id="debit-credit-cards">Debit/Credit Cards</h2><p> It is currently the most popular mode of payment in India. The reason behind this can be attributed to the safety, ease, and, accessibility in both online and offline modes. </p><h2 id="upi">UPI</h2><p>UPI stands for Unified Payments Interface. After debit/credit cards, UPI is the most popular mode of payments in India.</p><p>Launched in 2016, UPI has exponentially grown with a CAGR of 414%, clocking 1246 million transactions in March 2020. Since the imposition of lockdown last year, the number went to an all-time high of 1800 million in September 2020.</p><p>This can be seen as a result of the ease of the payments on these platforms as well as the tremendous marketing campaigns by the companies.</p><h2 id="aadhar-enabled-payment-system">Aadhar Enabled Payment System</h2><p>Under this, the Aadhar holder can transfer money from his Aadhar linked bank account to any other Aadhar linked bank account. Although India&#39;s 98% population already has an Aadhar card, it is still not quite popular.</p><p>Till February 2020, the transaction count of AEPS had crossed more than 205 million, according to NPCI.</p>`,
			img:
				'https://images.unsplash.com/photo-1605909568776-77fc14f43f0b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
			date: 'July 17, 2021'
		},
		{
			title: 'Digital Payments: The Need of the Hour',
			preview:
				'In the era of digitalization, the most affected area is the economic sector. Digital payments marked their beginning in 2016 with the demonetization and it has only been growing exponentially since then.',
			content: `<p><em>In the era of digitalization, the most affected area is the economic sector. Digital payments marked their beginning in 2016 with the demonetization and it has only been growing exponentially since then.</em> </p><p>You do not need to visit the bank each time you make a transaction. Digital payment allows you to transfer money from one account to another using a digital device. Platforms like Google Pay, Paytm, PhonePe, etc. are all over the place, especially amidst the pandemic. The pandemic caused a decline in the Cash-On Delivery method. Consequently, people started relying more upon online transactions. </p><p>Initially, cashless transactions were confined to metropolitan cities of the country, but social distancing norms and government schemes spread awareness among the people belonging to small towns. Nowadays, even tier-4 and tier-5 cities have adopted the contactless payment method using video KYC and Aadhar-enabled methods. </p><p>Along with providing financial accessibility, going cashless is relatively convenient, hassle-free, and easy to transact. It eliminates the struggle of standing in long queues in scorching weather and lets you conduct transactions with only a few clicks. Currently, over 300 million users in India prefer online payments through mobile banking as they offer &#39;tokenization&#39; wherein the card details are encrypted and provide a secured experience.</p>`,
			img:
				'https://images.unsplash.com/photo-1508960512160-5976980f6692?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
			date: 'July 18, 2021'
		},
		{
			title: 'The Rise of Digital Payments in India',
			preview:
				"By 2025, it is estimated that out of all payments, almost 71.7% of those, would be done digitally. Let's find out what is the driving force for this boom in these numbers.",
			content: `<p><em>By 2025, it is estimated that out of all payments, almost 71.7% of those, would be done digitally. Let&#39;s find out what is the driving force for this boom in these numbers.</em></p><h2 id="innovative-technologies">Innovative technologies</h2><p>The unfolding of new and improved technologies is one of the main factors for the growth of digital payments in India. Secure and easy-to-access technologies ensure greater opportunities to small time business owners and also guarantees safe and regulated transactions.</p><h2 id="increased-awareness-and-acceptance">Increased awareness and acceptance</h2><p>India&#39;s digital payments market has witnessed tremendous growth over the past few years, which has gained popularity especially after the demonetization in 2016. The people of India are now more comfortable with digital payments than ever before mostly due to the ease of payments and also with just a few clicks. The growing number of initiatives like UPI, BHIM, RuPay, introduction of QR Codes, and other easy payment options has led to the increase in acceptance and awareness about the changing digital payment ecosystem of the country.</p><h2 id="rising-e-commerce">Rising e-commerce</h2><p>Online transactions would continue to boost the digital payments market of the country. The Covid-19 pandemic saw customers taking to net banking and other digital payment facilities in categories like essential goods, groceries, retail, medical supplies, education, and others. Many e-commerce platforms are also promoting digital transactions by accepting payments only through online payment facilities.</p>`,
			img:
				'https://images.unsplash.com/photo-1560221328-12fe60f83ab8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1953&q=80',
			date: 'July 19, 2021'
		},
		{
			title: 'Protect Yourself from Scams!',
			preview:
				'Just like paper-based currency, an aware citizen must follow some basic rules and procedures to protect themselves from scams. Here are some common scams and guidelines to protect yourself from them:',
			content: `<p><em>Just like paper-based currency, an aware citizen must follow some basic rules and procedures to protect themselves from scams. Here are some common scams and guidelines to protect yourself from them:</em></p><ol>1. Beware of phishing: always download legitimate UPI applications from the bank&#39;s official website, and be cautious before you download it from Play/App store. </li><li>2. Keep strong passwords for your phone as well as for your UPI application.</li><li>3. Do not share MPIN with anybody (not even with the bank), and be suspicious of unknown callers claiming to be from your bank.</li><li>4. Use biometric authentication if possible.</li><li>5. Update your mobile OS and applications as often as possible to be secure from vulnerabilities.</li><li>6. It is advisable for users to enable encryption, remote wipe abilities and anti-virus software on the phone.</li><li>7. Keep your SIM card locked with a pin to avoid misuse. In case of loss or theft of your mobile device, contact your SIM provider to block the subscription of the SIM card.</li><li>8. Avoid connecting phones to unsecured wireless networks that do not need passwords to access.</li></ol>`,
			img:
				'https://images.unsplash.com/photo-1584433144859-1fc3ab64a957?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1788&q=80',
			date: 'July 20, 2021'
		}
	];
</script>
