<script lang="ts" context="module">
	// TODO: delete this placeholder when actual content is added
	const placeholderText: string = `<h1 id="sample-markdown">Sample Markdown</h1><p>Aliquam bibendum ac augue sed consectetur. Nulla nisl ante, iaculis ut velit at, suscipit pellentesque urna. Sed eu risus volutpat, ornare mi eget, scelerisque nisl. Proin mauris sapien, condimentum vitae turpis ac, iaculis porttitor lectus. Nullam dignissim lorem diam, sed lacinia est efficitur nec. Fusce quis dolor at arcu volutpat accumsan. Quisque eu magna ipsum.In velit justo, tempor nec sem vel, hendrerit commodo dui. Fusce ut augue at elit euismod mattis et et urna. Proin sit amet dolor varius, porttitor sapien sed, mattis massa. Aenean ut erat felis. Donec vulputate aliquam tellus, et tempus nunc varius vitae. Curabitur arcu mi, tristique ut molestie ut, mollis a diam. Phasellus rutrum tincidunt neque nec convallis. Maecenas rutrum turpis sed laoreet rutrum. Mauris nisi nulla, vehicula sit amet commodo sit amet, volutpat at ex. Praesent et velit eros. Nulla gravida nisl quis vulputate cursus. In dapibus nisl sed massa egestas, quis dapibus purus facilisis. Fusce luctus varius justo, sit amet ullamcorper lacus porta eget. Suspendisse in lectus nec dui posuere cursus eget id enim. Donec porttitor sapien ut est tempus, a aliquet elit hendrerit. In scelerisque ac diam id ultricies. Duis imperdiet maximus tincidunt. Maecenas condimentum suscipit purus, sed dictum ipsum elementum quis. Integer ut venenatis est. Fusce et ornare massa.</p><h2 id="second-heading">Second Heading</h2><ul><li>Unordered lists, and:<ol><li>One</li><li>Two</li><li>Three</li></ol></li><li>More</li></ul><blockquote><p>Blockquote</p></blockquote><p>And <strong>bold</strong>, <em>italics</em>, and even <em>italics and later <strong>bold</strong></em>. Even <del>strikethrough</del>. <a href="https://markdowntohtml.com">A link</a> to somewhere.</p><p>And code highlighting:</p><pre><code class="lang-js"><span class="hljs-keyword">var</span> foo = <span class="hljs-string">'bar'</span>;<span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">baz</span><span class="hljs-params">(s)</span> </span>{<span class="hljs-keyword">return</span> foo + <span class="hljs-string">':'</span> + s;}</code></pre><p>Or inline code like <code>var foo=&#39;bar&#39;;</code>.</p><p>Or an image of bears</p><p><img src="http://placebear.com/200/200" alt="bears"></p><p>The end ...</p>`;

	export const blog = [
		{
			title: "India's Journey Towards a Digital Economy",
			preview:
				'On November 8, 2016 the Government announced demonetization, the event that brought digital payments to the fore. Three years forward in 2019 RBI reported that the number of digital transactions has tripled, and now in 2021 the number of transactions has again doubled in volume.',
			content: `<h2>Introduction</h2><p>On November 8, 2016 the Government announced demonetization, the event that brought digital payments to the fore.</p><p>Three years forward in 2019 RBI reported that the number of digital transactions has tripled, and now in 2021 the number of transactions has again doubled in volume.</p><p>The long ATMs queues are becoming a rare sight. Shopkeepers, cab drivers, and street vendor are switching over to digital payments.</p><p>So, what happened? Why was there a sudden surge in digital transactions? And what does the future hold?</p><h2>Facts and Figures</h2><p>At the present rate of shift towards digital payment systems; 3 in every 4 transactions will be digital by 2025. This sudden momentum can be seen as a result of increasing technological advances in the financial system and events like demonetization and COVID lockdown which acted as a catalyst. The speed, safety, ease of payments attracts vendors and consumers equally.</p><p>Though the currency circulation was increased by 19.1 % in 2019 from the 2016 levels, the RBI norms on withdrawal limits, tariffs on ATM withdrawals, and intensive marketing campaigns by fintech companies has made India the top country in digital transactions by volume.</p><p>The most preferred form of digital payment presently is UPI (Unified Payment Interface) by debit/credit cards. The year 2020 marked a new record for UPI transactions in India. The total UPI transactions in 2020 reached the figure of 4,16,000 crores in 2020 which was a two-fold increase from the transactions in 2019. The pandemic forced many people to be accustomed to these formats, still it’s something that will benefit the economy in long run.</p><h2>Going Forward</h2><p>What does the future hold for digital payment? That&#39;s a really difficult question to answer, but it is sure that we’re not going back to the paper currency age.</p>`,
			img: 'https://images.unsplash.com/photo-1607434531924-050d4e675a44?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
			date: 'July 16, 2021'
		},
		{
			title: 'Blog #2',
			preview:
				'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae gravida ligula, ac rhoncus magna. Donec vulputate tellus eu justo mattis ultrices. Aliquam lectus lacus, congue eget sollicitudin a, lacinia a risus. Sed vulputate facilisis luctus. Suspendisse vitae metus nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam volutpat, turpis sit amet mattis sagittis, orci erat aliquet diam, id consectetur metus enim ut augue. Aenean vitae nulla lacus.',
			content: placeholderText,
			img: 'https://cdn.akamai.steamstatic.com/steam/apps/1293830/capsule_616x353.jpg',
			date: 'July 9, 2021'
		},
		{
			title: 'Blog #3',
			preview:
				'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae gravida ligula, ac rhoncus magna. Donec vulputate tellus eu justo mattis ultrices. Aliquam lectus lacus, congue eget sollicitudin a, lacinia a risus. Sed vulputate facilisis luctus. Suspendisse vitae metus nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam volutpat, turpis sit amet mattis sagittis, orci erat aliquet diam, id consectetur metus enim ut augue. Aenean vitae nulla lacus.',
			content: placeholderText,
			img: 'https://cdn.akamai.steamstatic.com/steam/apps/1293830/capsule_616x353.jpg',
			date: 'July 9, 2021'
		}
	];
</script>
